import { MessageSquare, Mic, Sparkles } from 'lucide-react'
import type { SymbolEntry } from 'lumi-help'

export const AI_SYMBOLS: SymbolEntry[] = [
  {
    id: 'ai.provider.gemini',
    label: 'Gemini',
    section: 'ai',
    icon: Sparkles,
    meaning: 'This message was generated by Google Gemini.',
    aliases: ['gemini', 'google', 'ai'],
  },
  {
    id: 'ai.voice',
    label: 'Voice assistant',
    section: 'ai',
    icon: Mic,
    meaning: 'Tap and speak to log or ask questions by voice.',
    aliases: ['voice', 'speak', 'assistant'],
  },
  {
    id: 'ai.chat',
    label: 'Chat with Lumina',
    section: 'ai',
    icon: MessageSquare,
    meaning: 'Ask Lumina a question in natural language.',
    aliases: ['chat', 'chatbot'],
  },
]
